language: ruby
sudo: false
rvm:
  - 2.4.1

install:
  - bundle install

script:
  - bundle exec jekyll build --future
  - bundle exec htmlproofer ./_site --only-4xx --check-html

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # Speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler

notifications:
  email: false
