language: ruby
sudo: false

matrix:
  include:
  - name: "RVM 2.4.1 Test"
    rvm: 2.4.1
    env: NAME="TEST"
  - name: "RVM 2.4.1 Lint"
    rvm: 2.4.1
    env: NAME="LINT"

install:
  - make setup
  - bundle exec bundle list

script:
  - if [[ $NAME == TEST ]]; then make test; fi
  - if [[ $NAME == LINT ]]; then make lint; fi

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # Speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler

notifications:
  email: false
