language: ruby
sudo: false
rvm:
  - 2.4.1

install: bundle install

script: ./scripts/build.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler

notifications:
  email: false
