# Jekyll Builder for GitHub Pages (Action)
# https://github.com/marketplace/actions/jekyll-builder-for-github-pages?version=v1
- name: build
  on: push
  uses: meitar/jekyll-builder-for-github-pages-action@v1
