name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Jekyll Builder for GitHub Pages (Action)
    # https://github.com/marketplace/actions/jekyll-builder-for-github-pages?version=v1
    - name: Build Jekyll site
      uses: meitar/jekyll-builder-for-github-pages-action@v1
